"use client";
import { useState, useEffect } from "react";
import Modal from "@/components/ui/Modal";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import { generateProductionJobCardPDF } from "@/lib/pdf-utils";
import { formatDateInput } from "@/lib/utils";

interface ProductionModalProps {
  open: boolean;
  onClose: () => void;
  onSubmit: (id: string, data: any) => Promise<void>;
  production: any;
  loading?: boolean;
}

export default function ProductionModal({
  open,
  onClose,
  onSubmit,
  production,
  loading,
}: ProductionModalProps) {
  const [remarks, setRemarks] = useState("");
  const [deliveryDate, setDeliveryDate] = useState("");

  useEffect(() => {
    if (open && production) {
      setRemarks(production.remarks || "");
      setDeliveryDate(production.deliveryDate ? formatDateInput(new Date(production.deliveryDate)) : "");
    }
  }, [open, production]);

  const handleFinalSubmit = async () => {
    await onSubmit(production._id, { remarks, deliveryDate });
    // PDF will be generated by the parent or here
    generateProductionJobCardPDF({
        ...production,
        remarks,
        deliveryDate
    });
  };

  if (!production) return null;

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Start Production Work"
      footer={
        <>
          <Button variant="outline" onClick={onClose} disabled={loading}>
            Cancel
          </Button>
          <Button onClick={handleFinalSubmit} loading={loading}>
            Start Work & Print Job Card
          </Button>
        </>
      }
    >
      <div className="space-y-6">
        {/* Read-only Item List */}
        <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
          <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">Items for Production</h4>
          <div className="space-y-3">
            {production.items.map((item: any, i: number) => (
              <div key={i} className="flex justify-between items-start border-b border-gray-100 pb-2 last:border-0 last:pb-0">
                <div>
                  <p className="text-sm font-semibold text-gray-900">{item.itemName}</p>
                  <p className="text-[10px] text-gray-500">
                    {item.color && `Color: ${item.color} | `}
                    {item.material && `Material: ${item.material} | `}
                    {item.size && `Size: ${item.size}`}
                  </p>
                </div>
                <span className="text-sm font-bold text-indigo-600">Qty: {item.quantity}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Delivery Date */}
        <Input 
          label="Target Delivery Date" 
          type="date" 
          value={deliveryDate} 
          onChange={(e) => setDeliveryDate(e.target.value)} 
          required 
          hint="Mention when the production should be finished"
        />

        {/* Big Remarks Field */}
        <div>
          <label className="text-sm font-medium text-gray-700 block mb-1.5">Special Instructions / Remarks</label>
          <textarea
            value={remarks}
            onChange={(e) => setRemarks(e.target.value)}
            placeholder="Add any specific details for the worker..."
            rows={5}
            className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all outline-none text-sm"
          />
        </div>
      </div>
    </Modal>
  );
}
